# Generated by Django 5.0a1 on 2023-10-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldOfCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                ("slug", models.SlugField(unique=True, verbose_name="code")),
                ("icon", models.CharField(max_length=200, verbose_name="icône")),
            ],
            options={
                "verbose_name": "domaine de compétence",
                "verbose_name_plural": "domaines de compétence",
            },
        ),
        migrations.CreateModel(
            name="ReferentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Au format +33 6 00 00 00 00",
                        max_length=200,
                        verbose_name="numéro de téléphone",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=200, verbose_name="ville"),
                ),
                (
                    "promotion",
                    models.CharField(
                        blank=True,
                        help_text="Au format X04 pour le cycle ingénieur polytechnicien, D98 pour le doctorat de Polytechnique, M09 pour le master, B22 pour le bachelor",
                        max_length=10,
                        verbose_name="promotion",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contact référent",
                "verbose_name_plural": "contacts référents",
            },
        ),
        migrations.CreateModel(
            name="RecommendedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="prénom")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="nom de famille"),
                ),
                ("website", models.URLField(blank=True, verbose_name="site personnel")),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="structure"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="fonction"
                    ),
                ),
                ("engagements", models.TextField(verbose_name="engagements")),
                (
                    "reasons_to_contact",
                    models.TextField(
                        blank=True,
                        verbose_name="raisons pour lesquelles on peut contacter cette personne",
                    ),
                ),
                (
                    "other_fields_of_competence",
                    models.CharField(
                        blank=True,
                        help_text="Sépare les domaines par des virgules, par exemple : Bilan carbone, Communication",
                        max_length=500,
                        verbose_name="autres domaines de compétence",
                    ),
                ),
                (
                    "fields_of_competence",
                    models.ManyToManyField(
                        blank=True,
                        to="contacts.fieldofcompetence",
                        verbose_name="domaines de compétence",
                    ),
                ),
                (
                    "referent_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contacts.referentcontact",
                        verbose_name="contact référent",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact recommandé",
                "verbose_name_plural": "contacts recommandés",
            },
        ),
    ]
