# Generated by Django 4.1.2 on 2022-10-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldOfCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("slug", models.SlugField(unique=True, verbose_name="Code")),
            ],
        ),
        migrations.CreateModel(
            name="ReferentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Nom de famille"),
                ),
                (
                    "mail",
                    models.EmailField(max_length=200, verbose_name="Adresse email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Au format +33 6 00 00 00 00",
                        max_length=200,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=200, verbose_name="Ville"),
                ),
                (
                    "promotion",
                    models.CharField(
                        blank=True,
                        help_text="Au format X04 pour le cycle ingénieur polytechnicien, D98 pour le doctorat de Polytechnique, M09 pour le master, B22 pour le bachelor",
                        max_length=200,
                        verbose_name="Promotion",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(verbose_name="Date d'inscription"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Nom de famille"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Site personnel"),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Structure"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fonction"
                    ),
                ),
                (
                    "engagements",
                    models.TextField(verbose_name="Engagements"),
                ),
                (
                    "reasons_to_contact",
                    models.TextField(
                        blank=True,
                        verbose_name="Raisons pour lesquelles on peut contacter cette personne",
                    ),
                ),
                (
                    "other_fields_of_competence",
                    models.CharField(
                        blank=True,
                        help_text="Sépare les domaines par des virgules, par exemple : Bilan carbone, Communication",
                        max_length=500,
                        verbose_name="Autres domaines de compétence",
                    ),
                ),
                (
                    "fields_of_competence",
                    models.ManyToManyField(
                        blank=True,
                        to="entrees.fieldofcompetence",
                        verbose_name="Domaines de compétence",
                    ),
                ),
                (
                    "referent_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entrees.referentcontact",
                        verbose_name="Contact référent",
                    ),
                ),
            ],
        ),
    ]
