# Generated by Django 4.1.2 on 2022-10-28 18:39
import json
from slugify import slugify

from django.db import migrations
from entrees import models


def create_fields(apps, schema_editor):
    Field = models.Field
    with open("./entrees/migrations/migration_files/fields.json", "r", encoding='utf8') as field_file:
        data = field_file.read()
    field_list = json.loads(data)
    for field_name in field_list:
        field = {
            "name": field_name,
            "slug": slugify(field_name, replacements=[['&', '-et-']])
        }
        Field.objects.create(**field)

def delete_fields(apps, schema_editor):
    models.Field.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("entrees", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_fields, delete_fields),]
