# Generated by Django 4.1.2 on 2022-12-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entrees", "0002_create_fields_of_competence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldofcompetence",
            options={
                "verbose_name": "domaine de compétence",
                "verbose_name_plural": "domaines de compétence",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendedcontact",
            options={
                "verbose_name": "contact recommandé",
                "verbose_name_plural": "contacts recommandés",
            },
        ),
        migrations.AlterModelOptions(
            name="referentcontact",
            options={
                "verbose_name": "contact référent",
                "verbose_name_plural": "contacts référents",
            },
        ),
        migrations.AlterField(
            model_name="fieldofcompetence",
            name="name",
            field=models.CharField(max_length=200, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="fieldofcompetence",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="engagements",
            field=models.TextField(verbose_name="engagements"),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="fields_of_competence",
            field=models.ManyToManyField(
                blank=True,
                to="entrees.fieldofcompetence",
                verbose_name="domaines de compétence",
            ),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="first_name",
            field=models.CharField(max_length=200, verbose_name="prénom"),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="function",
            field=models.CharField(blank=True, max_length=200, verbose_name="fonction"),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="nom de famille"),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="other_fields_of_competence",
            field=models.CharField(
                blank=True,
                help_text="Sépare les domaines par des virgules, par exemple : Bilan carbone, Communication",
                max_length=500,
                verbose_name="autres domaines de compétence",
            ),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="referent_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrees.referentcontact",
                verbose_name="contact référent",
            ),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="structure",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="structure"
            ),
        ),
        migrations.AlterField(
            model_name="recommendedcontact",
            name="website",
            field=models.URLField(blank=True, verbose_name="site personnel"),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="city",
            field=models.CharField(blank=True, max_length=200, verbose_name="ville"),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="first_name",
            field=models.CharField(max_length=200, verbose_name="prénom"),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="nom de famille"),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="mail",
            field=models.EmailField(max_length=200, verbose_name="adresse email"),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Au format +33 6 00 00 00 00",
                max_length=200,
                verbose_name="numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="promotion",
            field=models.CharField(
                blank=True,
                help_text="Au format X04 pour le cycle ingénieur polytechnicien, D98 pour le doctorat de Polytechnique, M09 pour le master, B22 pour le bachelor",
                max_length=200,
                verbose_name="promotion",
            ),
        ),
        migrations.AlterField(
            model_name="referentcontact",
            name="registration_date",
            field=models.DateTimeField(verbose_name="date d'inscription"),
        ),
    ]
